# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_advisory', models.BooleanField(default=False, help_text="Is this the teacher's homeroom/advisory class?")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_students', models.PositiveSmallIntegerField(default=50)),
                ('minutes_per_meeting', models.PositiveSmallIntegerField(default=60, help_text='Default duration per meeting in minutes.')),
                ('meetings_per_week', models.PositiveSmallIntegerField(default=5, help_text='Expected number of meetings per week.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_assignments', to=settings.AUTH_USER_MODEL)),
                ('default_room', models.ForeignKey(blank=True, help_text='Default classroom. Individual schedule entries can override this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_class_assignments', to='academics.room')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.section')),
                ('semester', models.ForeignKey(blank=True, help_text='Required for SHS subjects. NULL for JHS full-year subjects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Assignment',
                'verbose_name_plural': 'Class Assignments',
                'ordering': ['school_year', 'section__grade_level__sort_order', 'section__section_name', 'subject__subject_code'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('day_number', models.PositiveSmallIntegerField(editable=False, help_text='Auto-set from DAY_NUMBER_MAP in save().')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(editable=False, help_text='Auto-calculated from time_start and time_end.')),
                ('schedule_type', models.CharField(choices=[('Regular', 'Regular Class'), ('Makeup', 'Makeup Session'), ('Special', 'Special/Remedial Class'), ('Club', 'Club/Organization Meeting'), ('Other', 'Other')], default='Regular', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_until', models.DateField(blank=True, help_text='Leave blank for ongoing schedule. Set to retire this schedule entry.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.classassignment')),
                ('room', models.ForeignKey(blank=True, help_text='Overrides the default room from ClassAssignment if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to='academics.room')),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['day_number', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='SubstitutionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitution_date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, choices=[('Sick_Leave', 'Sick Leave'), ('Official_Business', 'Official Business / Training'), ('Personal_Leave', 'Personal Leave'), ('Emergency', 'Emergency'), ('Maternity_Leave', 'Maternity Leave'), ('Other', 'Other')], max_length=100)),
                ('reason_details', models.TextField(blank=True)),
                ('was_conducted', models.BooleanField(default=True, help_text='Did the class actually take place with the substitute?')),
                ('lesson_covered', models.TextField(blank=True, help_text='Brief description of what was taught during this period.')),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_substitutions', to=settings.AUTH_USER_MODEL)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='scheduling.classschedule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_substitutions', to=settings.AUTH_USER_MODEL)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_as_original', to=settings.AUTH_USER_MODEL)),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_as_substitute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substitution Assignment',
                'verbose_name_plural': 'Substitution Assignments',
                'ordering': ['-substitution_date', 'class_schedule__day_number', 'class_schedule__time_start'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLoadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sections', models.PositiveSmallIntegerField(default=0)),
                ('total_subjects', models.PositiveSmallIntegerField(default=0)),
                ('total_meetings_per_week', models.PositiveSmallIntegerField(default=0)),
                ('total_minutes_per_week', models.PositiveSmallIntegerField(default=0)),
                ('total_teaching_hours_per_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_adviser', models.BooleanField(default=False)),
                ('advised_section_name', models.CharField(blank=True, max_length=100)),
                ('is_overload', models.BooleanField(default=False, help_text='Exceeds DepEd maximum teaching load of 6 hours per day?')),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_load_summaries', to='academics.schoolyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Load Summary',
                'verbose_name_plural': 'Teacher Load Summaries',
                'ordering': ['school_year', 'teacher__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['teacher', 'school_year'], name='scheduling__teacher_f20418_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['section', 'school_year'], name='scheduling__section_62938b_idx'),
        ),
        migrations.AddIndex(
            model_name='classassignment',
            index=models.Index(fields=['is_active'], name='scheduling__is_acti_d07389_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classassignment',
            unique_together={('teacher', 'section', 'subject', 'school_year', 'semester')},
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['day_of_week', 'time_start'], name='scheduling__day_of__5f610d_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['is_active', 'day_number'], name='scheduling__is_acti_5ea966_idx'),
        ),
        migrations.AddIndex(
            model_name='substitutionassignment',
            index=models.Index(fields=['substitution_date'], name='scheduling__substit_a104f3_idx'),
        ),
        migrations.AddIndex(
            model_name='substitutionassignment',
            index=models.Index(fields=['original_teacher', 'substitution_date'], name='scheduling__origina_e416e0_idx'),
        ),
        migrations.AddIndex(
            model_name='substitutionassignment',
            index=models.Index(fields=['substitute_teacher', 'substitution_date'], name='scheduling__substit_a2e014_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherloadsummary',
            unique_together={('teacher', 'school_year')},
        ),
    ]
