# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepEdConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(help_text="e.g., 'LIS_API_ENDPOINT', 'BEIS_SCHOOL_ID', 'DIVISION_CODE', 'SYNC_FREQUENCY_HOURS'.", max_length=100, unique=True)),
                ('config_value', models.TextField()),
                ('config_type', models.CharField(choices=[('String', 'String'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('JSON', 'JSON'), ('URL', 'URL')], default='String', max_length=20)),
                ('category', models.CharField(choices=[('LIS_Integration', 'LIS Integration'), ('BEIS_Reporting', 'BEIS Reporting'), ('Division_Office', 'Division Office'), ('Dashboard', 'Dashboard'), ('Sync', 'Data Synchronization'), ('Security', 'Security'), ('Other', 'Other')], db_index=True, default='Other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False, help_text='Critical configurations that must be set for system operation.')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Sensitive values stored encrypted at rest (API keys, tokens).')),
                ('validation_regex', models.CharField(blank=True, help_text='Optional regex for value validation. Applied server-side with timeout to prevent ReDoS.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deped_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DepEd Configuration',
                'verbose_name_plural': 'DepEd Configurations',
                'ordering': ['category', 'config_key'],
                'indexes': [models.Index(fields=['category'], name='configurati_categor_596248_idx'), models.Index(fields=['is_required'], name='configurati_is_requ_786b80_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('Quarter', 'Quarter (Q1-Q4) — JHS'), ('Semester', 'Semester (1st-2nd) — SHS')], db_index=True, max_length=10)),
                ('report_card_type', models.CharField(choices=[('SF9_JHS', 'SF9 — Junior High School Report Card'), ('SF9_SHS', 'SF9 — Senior High School Report Card')], max_length=10)),
                ('is_grade_encoding_open', models.BooleanField(default=False, help_text='Can teachers encode grades for this period?')),
                ('grade_encoding_deadline', models.DateTimeField(blank=True, null=True)),
                ('grade_validation_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_grades_locked', models.BooleanField(default=False, help_text='Locked periods prevent any grade modification.')),
                ('weight_in_final_grade', models.DecimalField(blank=True, decimal_places=4, help_text='Weight in final grade: Q1-Q4 each = 0.2500. S1-S2 each = 0.5000.', max_digits=5, null=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Display/processing order: 1=Q1/S1, 2=Q2/S2, 3=Q3, 4=Q4.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.ForeignKey(blank=True, help_text="Required if period_type='Quarter'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_period_configs', to='academics.quarter')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_periods', to='academics.schoolyear')),
                ('semester', models.ForeignKey(blank=True, help_text="Required if period_type='Semester'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_period_configs', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Grading Period',
                'verbose_name_plural': 'Grading Periods',
                'ordering': ['school_year', 'order'],
                'indexes': [models.Index(fields=['is_grade_encoding_open'], name='configurati_is_grad_9e41ac_idx'), models.Index(fields=['is_grades_locked'], name='configurati_is_grad_06c649_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('quarter__isnull', False)), fields=('school_year', 'quarter'), name='unique_quarter_per_school_year'), models.UniqueConstraint(condition=models.Q(('semester__isnull', False)), fields=('school_year', 'semester'), name='unique_semester_per_school_year')],
            },
        ),
    ]
