# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text="e.g., 'Bachelor of Secondary Education', 'Master of Arts in Education'.", max_length=150)),
                ('major', models.CharField(blank=True, help_text="e.g., 'Major in Science', 'Major in Mathematics'.", max_length=150)),
                ('institution', models.CharField(help_text='College or university name.', max_length=255)),
                ('year_graduated', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('honors_received', models.CharField(blank=True, help_text="e.g., 'Cum Laude', 'Magna Cum Laude', 'Summa Cum Laude', 'With Distinction'.", max_length=150)),
                ('is_highest_degree', models.BooleanField(default=False, help_text="Is this the teacher's highest educational attainment?")),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, help_text='Scanned diploma or transcript.', null=True, upload_to='personnel/education/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_education_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Education Record',
                'verbose_name_plural': 'Teacher Education Records',
                'ordering': ['user__last_name', '-year_graduated'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAdvisoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(blank=True, help_text='When the teacher became adviser of this section.', null=True)),
                ('date_relieved', models.DateField(blank=True, help_text='When the teacher stopped being adviser (transferred, promoted, etc.).', null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Currently active advisory? Set False when relieved.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_assignments', to='academics.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_history', to='academics.section')),
                ('user', models.ForeignKey(help_text='The teacher who served as adviser.', on_delete=django.db.models.deletion.CASCADE, related_name='advisory_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Advisory History',
                'verbose_name_plural': 'Teacher Advisory History',
                'ordering': ['-school_year__year_start', 'user__last_name'],
                'indexes': [models.Index(fields=['is_current'], name='personnel_t_is_curr_1fc815_idx')],
                'unique_together': {('user', 'section', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('LET', 'Licensure Examination for Teachers'), ('PBET', 'Philippine Board Examination for Teachers'), ('Career_Service', 'Career Service Professional'), ('Bar_Board', 'Bar/Board Examination'), ('NC_II', 'TESDA NC II / NC III'), ('Other', 'Other')], max_length=30)),
                ('license_number', models.CharField(help_text='PRC License number or equivalent.', max_length=50)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, help_text='For renewal tracking. PRC licenses require renewal every 3 years.', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has the Registrar verified this license against PRC records?')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, help_text='Scanned copy of the license certificate.', null=True, upload_to='personnel/licenses/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The teacher who holds this license.', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher License',
                'verbose_name_plural': 'Teacher Licenses',
                'ordering': ['user__last_name', '-date_issued'],
                'indexes': [models.Index(fields=['license_type'], name='personnel_t_license_9e6221_idx'), models.Index(fields=['date_expiry'], name='personnel_t_date_ex_3653a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(help_text="e.g., 'Grade 7 Science Teacher', 'Grade 11-STEM Physics Teacher'.", max_length=255)),
                ('grade_levels_handled', models.CharField(blank=True, help_text="e.g., 'Grade 7, Grade 8' or 'Grade 11, Grade 12'.", max_length=100)),
                ('section_count', models.PositiveSmallIntegerField(default=0, help_text='Number of sections handled this school year.')),
                ('total_teaching_hours_per_week', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all class contact hours per week.', max_digits=5, null=True)),
                ('ancillary_designation', models.CharField(blank=True, help_text="e.g., 'Grade Level Chairperson', 'Science Department Head', 'Sports Coordinator', 'Yes-O Adviser'.", max_length=150)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, help_text='RPMS overall numerical rating for this school year (e.g., 4.25).', max_digits=4, null=True)),
                ('adjectival_rating', models.CharField(blank=True, choices=[('', 'Not Rated'), ('Outstanding', 'Outstanding (4.50-5.00)'), ('Very_Satisfactory', 'Very Satisfactory (3.50-4.49)'), ('Satisfactory', 'Satisfactory (2.50-3.49)'), ('Unsatisfactory', 'Unsatisfactory (1.50-2.49)'), ('Poor', 'Poor (Below 1.50)')], max_length=30)),
                ('awards_received', models.TextField(blank=True, help_text="e.g., 'Outstanding Teacher of the Year, Division Level'.")),
                ('is_completed', models.BooleanField(default=False, help_text='Has this service year been completed and verified?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_service_records', to='academics.schoolyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Service Record',
                'verbose_name_plural': 'Teacher Service Records',
                'ordering': ['user__last_name', '-school_year__year_start'],
                'unique_together': {('user', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(help_text="e.g., 'Division Training on RPMS-PPST for Teachers'.", max_length=255)),
                ('training_provider', models.CharField(blank=True, help_text="e.g., 'DepEd Division of Davao City', 'NEAP', 'SEAMEO INNOTECH'.", max_length=255)),
                ('training_type', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop / Hands-on Training'), ('Conference', 'Conference'), ('Online_Course', 'Online Course / MOOC'), ('Graduate_Study', 'Graduate Study'), ('INSET', 'In-Service Training (INSET)'), ('LAC', 'Learning Action Cell (LAC) Session'), ('Coaching', 'Coaching / Mentoring'), ('Other', 'Other')], max_length=30)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, help_text='Same as date_start for single-day events.', null=True)),
                ('hours_completed', models.DecimalField(blank=True, decimal_places=2, help_text='Total CPD units or training hours earned.', max_digits=6, null=True)),
                ('is_cpd_accredited', models.BooleanField(default=False, help_text='Is this training accredited by PRC for CPD units?')),
                ('cpd_accreditation_number', models.CharField(blank=True, max_length=50)),
                ('certificate_file', models.FileField(blank=True, help_text='Scanned certificate of completion.', null=True, upload_to='personnel/trainings/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Training Record',
                'verbose_name_plural': 'Teacher Training Records',
                'ordering': ['user__last_name', '-date_start'],
                'indexes': [models.Index(fields=['date_start'], name='personnel_t_date_st_f70029_idx'), models.Index(fields=['training_type'], name='personnel_t_trainin_b015ef_idx')],
            },
        ),
    ]
