# Generated by Django 6.0.6 on 2026-06-03 21:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ['school_year', 'quarter_number', 'quarter_label']},
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='year_level',
            field=models.IntegerField(blank=True, help_text='1=1st Year, 2=2nd Year, etc.', null=True),
        ),
        migrations.AddField(
            model_name='quarter',
            name='quarter_number',
            field=models.IntegerField(blank=True, help_text='1,2,3,4 for ordering', null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='term_system',
            field=models.CharField(choices=[('SEMESTRAL', 'Semestral (2 terms)'), ('TRIMESTRAL', 'Trimestral (3 terms)'), ('QUARTERLY', 'Quarterly (4 terms)')], default='SEMESTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, help_text='College/University Student ID', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(blank=True, help_text='1st Year, 2nd Year, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='grade_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='strand',
            field=models.CharField(blank=True, help_text='For SHS: STEM, ABM, HUMSS, etc. For College: Course/Major', max_length=100),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='quarter_label',
            field=models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter'), ('T1', 'First Trimester'), ('T2', 'Second Trimester'), ('T3', 'Third Trimester'), ('S1', 'First Semester'), ('S2', 'Second Semester'), ('SUMMER', 'Summer Term'), ('MIDYEAR', 'Midyear Term')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(help_text='DepEd/CHED School ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('ELEMENTARY', 'Elementary (Grades 1-6)'), ('JHS', 'Junior High School (Grades 7-10)'), ('SHS', 'Senior High School (Grades 11-12)'), ('INTEGRATED', 'Integrated School (K-12)'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('GRADUATE', 'Graduate School'), ('TVET', 'Technical and Vocational Education and Training'), ('SEMINARY', 'Seminary / Theological School'), ('ONLINE', 'Online University')], default='JHS', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('program_name', models.CharField(max_length=200)),
                ('degree_type', models.CharField(blank=True, choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BSE', 'Bachelor of Secondary Education'), ('BEEd', 'Bachelor of Elementary Education'), ('BSTM', 'Bachelor of Science in Tourism Management'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSA', 'Bachelor of Science in Accountancy'), ('BSBA', 'Bachelor of Science in Business Administration'), ('LLB', 'Bachelor of Laws'), ('JD', 'Juris Doctor'), ('MD', 'Doctor of Medicine'), ('MA', 'Master of Arts'), ('MS', 'Master of Science'), ('PhD', 'Doctor of Philosophy'), ('CERT', 'Certificate Program'), ('DIP', 'Diploma Program')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('duration_years', models.IntegerField(default=4, help_text='Number of years to complete')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admin_panel.school')),
            ],
            options={
                'ordering': ['program_code'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_panel.program'),
        ),
    ]
