# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_work_raw', models.DecimalField(decimal_places=2, help_text='Sum of all written work scores (quizzes, long tests, essays, homework). Must be 0-100.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('written_work_max', models.DecimalField(decimal_places=2, help_text='Maximum possible written work total. Must be between 1-100.', max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('written_work_percent', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='(written_work_raw / written_work_max) * 100. Auto-computed.', max_digits=5, null=True)),
                ('written_work_weighted', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='written_work_percent * WW weight (e.g., 30% for JHS core). Auto-computed.', max_digits=5, null=True)),
                ('performance_task_raw', models.DecimalField(decimal_places=2, help_text='Sum of all performance task scores (projects, presentations, lab work). Must be 0-100.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance_task_max', models.DecimalField(decimal_places=2, help_text='Maximum possible performance task total. Must be between 1-100.', max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('performance_task_percent', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('performance_task_weighted', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('quarterly_assessment_raw', models.DecimalField(decimal_places=2, help_text='Periodical examination score. Must be 0-100.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quarterly_assessment_max', models.DecimalField(decimal_places=2, help_text='Maximum possible quarterly assessment total. Must be between 1-100.', max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('quarterly_assessment_percent', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('quarterly_assessment_weighted', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('initial_grade', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Sum of all three weighted scores. Auto-computed.', max_digits=5, null=True)),
                ('transmuted_grade', models.PositiveSmallIntegerField(blank=True, help_text='Quarterly grade after applying DepEd transmutation table (60-100). Auto-computed.', null=True)),
                ('descriptor', models.CharField(blank=True, choices=[('Outstanding', 'Outstanding (90-100)'), ('Very_Satisfactory', 'Very Satisfactory (85-89)'), ('Satisfactory', 'Satisfactory (80-84)'), ('Fairly_Satisfactory', 'Fairly Satisfactory (75-79)'), ('Did_Not_Meet_Expectations', 'Did Not Meet Expectations (Below 75)')], help_text='Grade descriptor per DepEd Order 8, s. 2015.', max_length=30)),
                ('encoding_date', models.DateTimeField(auto_now_add=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft — Teacher still encoding'), ('Submitted', 'Submitted for Validation'), ('Validated', 'Validated by Registrar'), ('Returned', 'Returned for Correction'), ('Finalized', 'Finalized — Locked')], db_index=True, default='Draft', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True, help_text="Registrar's notes during validation.")),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoded_by', models.ForeignKey(blank=True, help_text='Subject teacher who encoded these grades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_grades', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(help_text='The enrollment record for this school year.', on_delete=django.db.models.deletion.CASCADE, related_name='grade_components', to='enrollment.enrollment')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_grades', to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(help_text='Grading quarter (Q1-Q4).', on_delete=django.db.models.deletion.PROTECT, related_name='grade_components', to='academics.quarter')),
                ('semester', models.ForeignKey(blank=True, help_text='For SHS: the semester this grade belongs to. NULL for JHS year-long subjects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_components', to='academics.semester')),
                ('subject', models.ForeignKey(help_text='The subject being graded.', on_delete=django.db.models.deletion.PROTECT, related_name='grade_components', to='academics.subject')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Component',
                'verbose_name_plural': 'Grade Components',
                'ordering': ['quarter', 'subject__subject_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(help_text="Name of the field that was modified: 'written_work_raw', 'transmuted_grade', etc.", max_length=50)),
                ('old_value', models.CharField(blank=True, help_text='Previous value as string. NULL if field was previously empty.', max_length=50, null=True)),
                ('new_value', models.CharField(help_text='New value as string.', max_length=50)),
                ('change_reason', models.TextField(blank=True, help_text='Required for audit compliance — why was this grade changed?')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change.', on_delete=django.db.models.deletion.PROTECT, related_name='grade_changes', to=settings.AUTH_USER_MODEL)),
                ('grade_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='grades.gradecomponent')),
            ],
            options={
                'verbose_name': 'Grade Change Log',
                'verbose_name_plural': 'Grade Change Logs',
                'ordering': ['grade_component', '-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='HonorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('Quarterly', 'Quarterly Honors'), ('End_of_Year', 'End of School Year Honors')], db_index=True, default='Quarterly', max_length=20)),
                ('honor_level', models.CharField(choices=[('With_Honors', 'With Honors (90-94)'), ('With_High_Honors', 'With High Honors (95-97)'), ('With_Highest_Honors', 'With Highest Honors (98-100)')], db_index=True, max_length=30)),
                ('general_average', models.DecimalField(decimal_places=2, help_text='General average that qualified for this honor.', max_digits=5)),
                ('awarded_date', models.DateField(default=django.utils.timezone.now)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='grades/honors/certificates/%Y/')),
                ('is_withdrawn', models.BooleanField(db_index=True, default=False, help_text='Was the honor later withdrawn? Record is kept for audit history.')),
                ('withdrawn_reason', models.TextField(blank=True, help_text='Reason for withdrawal: disciplinary action, grade correction, etc.')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_records', to='enrollment.enrollment')),
                ('quarter', models.ForeignKey(blank=True, help_text='NULL for End-of-School-Year honors. Set for Quarterly honors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honor_records', to='academics.quarter')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_honors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honor Record',
                'verbose_name_plural': 'Honor Records',
                'ordering': ['-enrollment__school_year__year_start', 'quarter__quarter_number', 'enrollment__student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, help_text='Average of all transmuted subject grades for this quarter.', max_digits=5, null=True)),
                ('total_subjects', models.PositiveSmallIntegerField(default=0)),
                ('subjects_passed', models.PositiveSmallIntegerField(default=0, help_text='Subjects with transmuted grade ≥ 75.')),
                ('subjects_failed', models.PositiveSmallIntegerField(default=0, help_text='Subjects with transmuted grade < 75.')),
                ('has_failing_grade', models.BooleanField(default=False, help_text='True if any subject grade is below 75. Disqualifies from honors.')),
                ('has_grade_below_85', models.BooleanField(default=False, help_text='True if any subject is below 85. Disqualifies from With High/Highest Honors.')),
                ('honor_eligible', models.BooleanField(db_index=True, default=False, help_text='Meets all criteria for quarterly honors per DepEd Order.')),
                ('honor_level', models.CharField(blank=True, choices=[('With_Honors', 'With Honors (90-94)'), ('With_High_Honors', 'With High Honors (95-97)'), ('With_Highest_Honors', 'With Highest Honors (98-100)')], max_length=30)),
                ('is_complete', models.BooleanField(default=False, help_text='All subject grades for this quarter have been submitted and validated.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_grades', to='enrollment.enrollment')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_grades', to='academics.quarter')),
            ],
            options={
                'verbose_name': 'Quarterly Grade',
                'verbose_name_plural': 'Quarterly Grades',
                'ordering': ['quarter', 'enrollment__student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('q2_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('q3_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('q4_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Average of all non-null quarter grades.', max_digits=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('Passed', 'Passed (≥75)'), ('Failed', 'Failed (<75)'), ('Incomplete', 'Incomplete — Missing one or more quarters')], max_length=20, null=True)),
                ('is_general_average', models.BooleanField(db_index=True, default=False, help_text='True if this record is the General Average (subject=NULL). False if per-subject final grade.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='enrollment.enrollment')),
                ('subject', models.ForeignKey(blank=True, help_text='NULL if this is the General Average record. Set for per-subject final grades.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_grades', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Final Grade',
                'verbose_name_plural': 'Final Grades',
                'ordering': ['enrollment__student__last_name', 'subject__subject_name'],
                'indexes': [models.Index(fields=['is_general_average'], name='grades_fina_is_gene_297104_idx'), models.Index(fields=['status'], name='grades_fina_status_61442d_idx')],
                'unique_together': {('enrollment', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='gradecomponent',
            index=models.Index(fields=['validation_status'], name='grades_grad_validat_905bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecomponent',
            index=models.Index(fields=['enrollment', 'quarter'], name='grades_grad_enrollm_005b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecomponent',
            index=models.Index(fields=['is_locked'], name='grades_grad_is_lock_a043cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradecomponent',
            unique_together={('enrollment', 'subject', 'quarter')},
        ),
        migrations.AddIndex(
            model_name='gradechangelog',
            index=models.Index(fields=['grade_component', 'created_at'], name='grades_grad_grade_c_4eb7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='gradechangelog',
            index=models.Index(fields=['changed_by', 'created_at'], name='grades_grad_changed_271830_idx'),
        ),
        migrations.AddIndex(
            model_name='honorrecord',
            index=models.Index(fields=['award_type'], name='grades_hono_award_t_d4f796_idx'),
        ),
        migrations.AddIndex(
            model_name='honorrecord',
            index=models.Index(fields=['honor_level'], name='grades_hono_honor_l_78b609_idx'),
        ),
        migrations.AddIndex(
            model_name='honorrecord',
            index=models.Index(fields=['is_withdrawn'], name='grades_hono_is_with_80a6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='quarterlygrade',
            index=models.Index(fields=['honor_eligible'], name='grades_quar_honor_e_41a11b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quarterlygrade',
            unique_together={('enrollment', 'quarter')},
        ),
    ]
