# Generated by Django 6.0.6 on 2026-06-08 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subjectfamily_subject_subject_family'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='beis_school_id',
            field=models.CharField(blank=True, help_text='BEIS School ID — for LIS interoperability and DepEd reporting.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Assigned school for role-based data access. NULL for system admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='academics.school'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_regularized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/signatures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_homeroom_adviser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Specific expertise.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_area',
            field=models.CharField(blank=True, help_text='Primary subject area.', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_of_service',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['school', 'role'], name='accounts_us_school__c18643_idx'),
        ),
    ]
