# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('Academic', 'Academic'), ('Administrative', 'Administrative'), ('Event', 'Event'), ('Emergency', 'Emergency'), ('Deadline', 'Deadline')], max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('All', 'All Users'), ('Role', 'By Role'), ('Section', 'By Section'), ('Grade_Level', 'By Grade Level'), ('Individual', 'Individual User')], max_length=20)),
                ('target_role', models.CharField(blank=True, choices=[('admin', 'System Administrator'), ('schoolhead', 'School Head / Principal'), ('registrar', 'School Registrar'), ('teacher', 'Teacher')], help_text="Required if target_type='Role'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='communication.announcement')),
                ('target_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_targets', to='academics.gradelevel')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_targets', to='academics.section')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Target',
                'verbose_name_plural': 'Announcement Targets',
                'ordering': ['announcement', 'target_type'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='communication.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement View',
                'verbose_name_plural': 'Announcement Views',
                'ordering': ['announcement', '-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_threads', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Thread',
                'verbose_name_plural': 'Message Threads',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='NULL if message to all thread participants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.messagethread')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['thread', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GRADE_RETURNED', 'Registrar returned grades for correction'), ('GRADE_VALIDATED', 'Registrar validated submitted grades'), ('GRADE_DEADLINE_REMINDER', 'Approaching grade encoding deadline'), ('FORM_SUBMISSION_DEADLINE', 'SF1/SF2/SF9 submission due soon'), ('FORM_RETURNED', 'Submitted form returned for revision'), ('FORM_APPROVED', 'Form approved by registrar/head'), ('ANNOUNCEMENT_POSTED', 'New announcement posted'), ('ANNOUNCEMENT_URGENT', 'Urgent announcement'), ('TRANSFER_REQUEST', 'New transfer request needs action'), ('TRANSFER_APPROVED', 'Transfer approved'), ('TRANSFER_DOCUMENTS_READY', 'SF9/SF10 ready for pickup'), ('MESSAGE_RECEIVED', 'New message received'), ('ATTENDANCE_ALERT', 'Student reached 20% absence threshold'), ('ENROLLMENT_CONFIRMATION', 'Student enrollment processed'), ('PROMOTION_REVIEW_NEEDED', 'Promotion recommendations ready for review'), ('EVALUATION_SCHEDULED', 'RPMS observation scheduled'), ('EVALUATION_COMPLETED', 'Evaluation results available'), ('SYSTEM_MAINTENANCE', 'Scheduled system downtime'), ('SYSTEM_UPDATE', 'New feature or update available')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_published'], name='communicati_is_publ_1b4801_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['priority'], name='communicati_priorit_50c09c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category'], name='communicati_categor_3680e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementview',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='communicati_thread__a03562_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='communicati_sender__9b3871_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='communicati_is_read_d3b61c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='communicati_recipie_e3882c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='communicati_recipie_4d94e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='communicati_notific_6be787_idx'),
        ),
    ]
