# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField(help_text='Sequential block number (0 = genesis block).', unique=True)),
                ('previous_hash', models.CharField(max_length=66)),
                ('current_hash', models.CharField(help_text="SHA-256 hash of this block's contents.", max_length=66, unique=True)),
                ('merkle_root', models.CharField(help_text='Merkle tree root hash of all activity log IDs in this block.', max_length=66)),
                ('log_count', models.PositiveIntegerField()),
                ('log_ids', models.JSONField(help_text='Array of activity_log IDs included in this block (in order).')),
                ('nonce', models.BigIntegerField(help_text='Proof-of-work nonce.')),
                ('mined_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blockchain Block',
                'verbose_name_plural': 'Blockchain Blocks',
                'ordering': ['block_index'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_name', models.CharField(help_text="Denormalized — user's full name at time of action.", max_length=150)),
                ('user_role', models.CharField(help_text="Denormalized — user's role at time of action.", max_length=30)),
                ('action_type', models.CharField(db_index=True, help_text="e.g., 'CREATE_STUDENT', 'UPDATE_GRADE', 'DELETE_ENROLLMENT', 'LOGIN_SUCCESS', 'EXPORT_DATA'.", max_length=50)),
                ('resource_type', models.CharField(help_text="Model/table affected: 'Student', 'GradeComponent', 'Enrollment'.", max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('details_json', models.JSONField(blank=True, help_text="Full change details: {'field': 'status', 'old': 'Enrolled', 'new': 'Transferred Out'}.", null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('blockchain_hash', models.CharField(help_text='SHA-256 hash of this entry.', max_length=66, unique=True)),
                ('prev_blockchain_hash', models.CharField(help_text='Hash of the previous activity log entry — forms the chain.', max_length=66)),
                ('blockchain_verified', models.BooleanField(default=True, help_text='Set False if tampering detected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='students.student')),
                ('affected_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs_as_teacher', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.sessionlog')),
                ('user', models.ForeignKey(blank=True, help_text='NULL for system-generated actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('Unusual_Grade_Change', 'Unusual Grade Change'), ('Suspicious_Login', 'Suspicious Login'), ('Data_Tampering', 'Data Tampering'), ('Bulk_Delete', 'Bulk Delete'), ('Unauthorized_Access', 'Unauthorized Access'), ('Pattern_Deviation', 'Pattern Deviation'), ('Fraud_Indicator', 'Fraud Indicator')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, max_length=15)),
                ('confidence_score', models.DecimalField(decimal_places=4, help_text='AI model confidence: 0.0000 (none) to 1.0000 (absolute certainty).', max_digits=5)),
                ('model_version', models.CharField(help_text="Version of AI model that flagged this: 'v1.0.0', 'v2.1.3'.", max_length=20)),
                ('details_json', models.JSONField(blank=True, help_text='Full anomaly details: features analyzed, threshold exceeded, pattern matched.', null=True)),
                ('is_investigated', models.BooleanField(db_index=True, default=False)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_result', models.CharField(blank=True, choices=[('Confirmed_Anomaly', 'Confirmed Anomaly'), ('False_Positive', 'False Positive'), ('Inconclusive', 'Inconclusive')], max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_investigations', to=settings.AUTH_USER_MODEL)),
                ('triggering_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='audit.activitylog')),
            ],
            options={
                'verbose_name': 'Anomaly Detection Event',
                'verbose_name_plural': 'Anomaly Detection Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text="Model/table: 'Student', 'GradeComponent', 'Enrollment', 'AttendanceRecord'.", max_length=50)),
                ('entity_id', models.PositiveIntegerField(help_text='ID of the record to correct.')),
                ('field_to_correct', models.CharField(max_length=100)),
                ('current_value', models.TextField()),
                ('proposed_value', models.TextField()),
                ('justification', models.TextField(help_text='Detailed reason for correction. Required for audit compliance.')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved — Correction Applied'), ('Denied', 'Denied'), ('Executed', 'Executed — Data Updated')], db_index=True, default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_by', models.ForeignKey(blank=True, help_text='User who actually applied the correction to the database.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests_executed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Correction Request',
                'verbose_name_plural': 'Data Correction Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_activ_action__26a287_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_activ_resourc_7bdc49_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['affected_student', 'timestamp'], name='audit_activ_affecte_28d7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['blockchain_verified'], name='audit_activ_blockch_81b822_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionevent',
            index=models.Index(fields=['anomaly_type', 'severity'], name='audit_anoma_anomaly_88b964_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionevent',
            index=models.Index(fields=['is_investigated'], name='audit_anoma_is_inve_61e80e_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionevent',
            index=models.Index(fields=['confidence_score'], name='audit_anoma_confide_ac129d_idx'),
        ),
        migrations.AddIndex(
            model_name='datacorrectionrequest',
            index=models.Index(fields=['status'], name='audit_datac_status_53ec3a_idx'),
        ),
        migrations.AddIndex(
            model_name='datacorrectionrequest',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_datac_entity__d440ba_idx'),
        ),
    ]
