# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('INCOMING', 'Incoming — Transferring into this school'), ('OUTGOING', 'Outgoing — Transferring to another school')], db_index=True, max_length=10)),
                ('from_school_name', models.CharField(blank=True, max_length=255)),
                ('from_school_beis_id', models.CharField(blank=True, max_length=20)),
                ('from_school_address', models.CharField(blank=True, max_length=255)),
                ('to_school_name', models.CharField(blank=True, max_length=255)),
                ('to_school_beis_id', models.CharField(blank=True, max_length=20)),
                ('to_school_address', models.CharField(blank=True, max_length=255)),
                ('transfer_date_requested', models.DateField(db_index=True)),
                ('transfer_date_effective', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('Change_of_Residence', 'Change of Residence'), ('Parent_Employment', 'Parent Employment / Relocation'), ('Academic', 'Academic Reasons'), ('Discipline', 'Disciplinary'), ('Financial', 'Financial Difficulties'), ('Health', 'Health Reasons'), ('Safety', 'Safety / Bullying / Emergency'), ('Proximity', 'Closer to Home'), ('Other', 'Other')], max_length=30)),
                ('reason_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending — Request initiated'), ('Documents_Requested', 'Documents Requested'), ('Documents_Released', 'Documents Released'), ('Approved', 'Approved by Receiving School'), ('Completed', 'Completed — Learner enrolled/withdrawn'), ('Denied', 'Denied'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=25)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sf9_released', models.BooleanField(default=False)),
                ('sf9_release_date', models.DateField(blank=True, null=True)),
                ('sf10_released', models.BooleanField(default=False)),
                ('sf10_release_date', models.DateField(blank=True, null=True)),
                ('enrollment_updated', models.BooleanField(default=False, help_text='Has enrollment status been updated for this transfer?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('grade_level_at_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='academics.gradelevel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='students.student')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-transfer_date_requested', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SF9', 'SF9 — Report Card'), ('SF10', 'SF10 — Form 137 (Permanent Record)'), ('Good_Moral', 'Certificate of Good Moral Character'), ('Birth_Certificate', 'PSA Birth Certificate'), ('Letter_of_Acceptance', 'Letter of Acceptance'), ('Other', 'Other')], max_length=25)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='transfers/documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transfers.transfer')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transfer_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Document',
                'verbose_name_plural': 'Transfer Documents',
                'ordering': ['transfer', 'document_type'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='transfers_t_status_91e571_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_type', 'status'], name='transfers_t_transfe_77b45c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_date_requested'], name='transfers_t_transfe_317198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferdocument',
            unique_together={('transfer', 'document_type')},
        ),
    ]
