# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollment', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField(help_text='Date of the graduation/recognition ceremony.')),
                ('graduation_type', models.CharField(choices=[('JHS_Completion', 'Junior High School Completion'), ('SHS_Graduation', 'Senior High School Graduation')], db_index=True, help_text='JHS Completion or SHS Graduation.', max_length=20)),
                ('diploma_number', models.CharField(blank=True, help_text='Unique diploma/certificate serial number.', max_length=50, null=True, unique=True)),
                ('honors_at_graduation', models.CharField(blank=True, choices=[('', 'No Honors'), ('With_Honors', 'With Honors'), ('With_High_Honors', 'With High Honors'), ('With_Highest_Honors', 'With Highest Honors')], help_text='Honors earned at graduation.', max_length=30)),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, help_text='Final General Average used for honors determination.', max_digits=5, null=True)),
                ('certificate_issued', models.BooleanField(default=False, help_text='Has the diploma/certificate been issued to the student?')),
                ('certificate_issued_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Scanned copy of the issued certificate.', null=True, upload_to='promotion/graduation/certificates/%Y/')),
                ('is_verified', models.BooleanField(default=False, help_text='Graduation verified by Registrar and School Head.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sf10_updated', models.BooleanField(default=False, help_text='Has SF10 (Form 137) been updated with this graduation information?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level_completed', models.ForeignKey(help_text='Grade level completed: Grade 10 (JHS Completion) or Grade 12 (SHS Graduation).', on_delete=django.db.models.deletion.PROTECT, related_name='graduation_records', to='academics.gradelevel')),
                ('school_year', models.ForeignKey(help_text='School year of graduation.', on_delete=django.db.models.deletion.PROTECT, related_name='graduation_records', to='academics.schoolyear')),
                ('strand_completed', models.ForeignKey(blank=True, help_text='Strand completed — SHS only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_records', to='academics.strand')),
                ('student', models.ForeignKey(help_text='The student who graduated/completed.', on_delete=django.db.models.deletion.PROTECT, related_name='graduation_records', to='students.student')),
                ('track_completed', models.ForeignKey(blank=True, help_text='Track completed — SHS only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_records', to='academics.track')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_graduations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduation Record',
                'verbose_name_plural': 'Graduation Records',
                'ordering': ['-graduation_date', 'student__last_name'],
                'indexes': [models.Index(fields=['graduation_type'], name='promotion_g_graduat_49a0d7_idx'), models.Index(fields=['graduation_date'], name='promotion_g_graduat_72e1de_idx'), models.Index(fields=['diploma_number'], name='promotion_g_diploma_562b1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromotionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('Promoted', 'Promoted — All subjects passed'), ('Conditionally_Promoted', 'Conditionally Promoted — Failed 1-2 subjects, must pass remedial classes'), ('Retained', 'Retained — Failed >2 subjects or failed remedial')], help_text="Adviser's initial promotion recommendation.", max_length=25)),
                ('recommendation_date', models.DateField(blank=True, null=True)),
                ('total_subjects', models.PositiveSmallIntegerField(default=0, help_text='Total subjects taken this school year.')),
                ('subjects_passed', models.PositiveSmallIntegerField(default=0)),
                ('subjects_failed', models.PositiveSmallIntegerField(default=0)),
                ('failed_subjects_list', models.TextField(blank=True, help_text="Names of failed subjects, e.g., 'Mathematics 10, Science 10'.")),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, help_text='Final General Average from FinalGrade.', max_digits=5, null=True)),
                ('remedial_required', models.BooleanField(default=False, help_text='True if conditionally promoted — must pass remedial classes.')),
                ('remedial_subjects', models.TextField(blank=True, help_text='Subjects the student must take remedial classes for.')),
                ('remedial_deadline', models.DateField(blank=True, help_text='Deadline to complete remedial classes (typically before next SY starts).', null=True)),
                ('remedial_completed', models.BooleanField(default=False, help_text='Did the student pass the remedial classes?')),
                ('remedial_completed_date', models.DateField(blank=True, null=True)),
                ('final_decision', models.CharField(blank=True, choices=[('Promoted', 'Promoted — All subjects passed'), ('Conditionally_Promoted', 'Conditionally Promoted — Failed 1-2 subjects, must pass remedial classes'), ('Retained', 'Retained — Failed >2 subjects or failed remedial')], help_text='Final decision after review and remedial results. Set by Registrar. Overrides initial recommendation if different.', max_length=25, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft — Adviser preparing'), ('Submitted', 'Submitted to Registrar'), ('Reviewed', 'Reviewed by Registrar'), ('Approved', 'Approved by School Head'), ('Finalized', 'Finalized — Recorded in SF10')], db_index=True, default='Draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text="Registrar's notes during review.")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sf10_updated', models.BooleanField(default=False, help_text='Has the SF10 permanent record been updated with this promotion decision?')),
                ('sf10_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='School Head who gave final approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_recommendations_approved', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(help_text='The enrollment record this promotion decision applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_recommendation', to='enrollment.enrollment')),
                ('recommended_by', models.ForeignKey(help_text='Class adviser who made the recommendation.', on_delete=django.db.models.deletion.PROTECT, related_name='promotion_recommendations_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Registrar who reviewed the recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_recommendations_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Recommendation',
                'verbose_name_plural': 'Promotion Recommendations',
                'ordering': ['enrollment__student__last_name'],
                'indexes': [models.Index(fields=['recommendation'], name='promotion_p_recomme_96dab7_idx'), models.Index(fields=['final_decision'], name='promotion_p_final_d_944d4b_idx'), models.Index(fields=['status'], name='promotion_p_status_752238_idx'), models.Index(fields=['remedial_required'], name='promotion_p_remedia_1b32f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Academic_Failure', 'Academic Failure — Failed >2 subjects'), ('Failed_Remedial', 'Failed Remedial — Did not pass summer/remedial classes'), ('Excessive_Absences', 'Excessive Absences — ≥20% of school days missed'), ('Parental_Request', 'Parental/Guardian Request'), ('Health', 'Health Reasons — Extended illness'), ('Other', 'Other')], help_text='Primary reason for retention.', max_length=25)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation of why the student is being retained.')),
                ('intervention_attempted', models.BooleanField(default=False, help_text='Were interventions attempted before retention? (Tutoring, counseling, parent conference, home visit).')),
                ('intervention_details', models.TextField(blank=True, help_text='Description of interventions attempted and their outcomes.')),
                ('parent_notified', models.BooleanField(default=False, help_text='Was the parent/guardian formally notified of the retention decision?')),
                ('parent_notification_date', models.DateField(blank=True, null=True)),
                ('parent_response', models.TextField(blank=True, help_text="Parent/guardian's acknowledgment or response to the retention.")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='School Head who approved the retention.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retentions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(help_text='The enrollment for the school year the student is being retained.', on_delete=django.db.models.deletion.CASCADE, related_name='retention_record', to='enrollment.enrollment')),
                ('next_school_year', models.ForeignKey(help_text='School year the student will repeat the grade level.', on_delete=django.db.models.deletion.PROTECT, related_name='retained_students', to='academics.schoolyear')),
                ('recorded_by', models.ForeignKey(help_text='Registrar who recorded this retention.', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_retentions', to=settings.AUTH_USER_MODEL)),
                ('retained_grade_level', models.ForeignKey(help_text='Grade level the student will repeat (same as current grade level).', on_delete=django.db.models.deletion.PROTECT, related_name='retained_students', to='academics.gradelevel')),
            ],
            options={
                'verbose_name': 'Retention Record',
                'verbose_name_plural': 'Retention Records',
                'ordering': ['enrollment__student__last_name'],
                'indexes': [models.Index(fields=['reason'], name='promotion_r_reason_323658_idx'), models.Index(fields=['next_school_year'], name='promotion_r_next_sc_f0362b_idx')],
            },
        ),
    ]
