# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('enrollment_type', models.CharField(choices=[('New', 'New Enrollee — First time in this school'), ('Continuing', 'Continuing — Previously enrolled last SY'), ('Transferred_In', 'Transferred In — From another school'), ('Balik_Aral', 'Balik-Aral — Returning after dropping out'), ('ALS_Passer', 'ALS Passer — Alternative Learning System completer')], db_index=True, max_length=25)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled — Currently active'), ('Transferred_In', 'Transferred In — Recently moved in'), ('Transferred_Out', 'Transferred Out — Moved to another school'), ('Graduated', 'Graduated — Completed the grade level'), ('Dropped', 'Dropped — Officially dropped out'), ('Inactive', 'Inactive — Not currently attending'), ('Deceased', 'Deceased — Learner has passed away')], db_index=True, default='Enrolled', max_length=25)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=255)),
                ('previous_school_beis_id', models.CharField(blank=True, max_length=20)),
                ('previous_school_address', models.CharField(blank=True, max_length=255)),
                ('is_balik_aral', models.BooleanField(default=False)),
                ('years_out_of_school', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_4ps', models.BooleanField(default=False)),
                ('esc_grantee', models.BooleanField(default=False)),
                ('voucher_program', models.CharField(blank=True, choices=[('', 'None'), ('SHS_VP', 'SHS Voucher Program'), ('ESC', 'Educational Service Contracting'), ('QVR', 'Qualified Voucher Recipient'), ('EVP', 'Education Voucher Program')], max_length=50)),
                ('voucher_number', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('grade_level_at_entry', models.ForeignKey(blank=True, help_text='Auto-set from section.grade_level in save().', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments_at_this_level', to='academics.gradelevel')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['school_year', 'section__grade_level__sort_order', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DroppedStudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropout_date', models.DateField()),
                ('dropout_reason', models.CharField(choices=[('Financial', 'Financial Difficulty'), ('Employment', 'Found Employment'), ('Family_Responsibility', 'Family Responsibility / Caregiving'), ('Health', 'Health Reasons'), ('Distance', 'Distance / Accessibility of School'), ('Academic_Difficulty', 'Academic Difficulty'), ('Disinterest', 'Lack of Interest / Motivation'), ('Bullying', 'Bullying / Peer Issues'), ('Early_Marriage', 'Early Marriage / Pregnancy'), ('Relocation', 'Family Relocation'), ('Discipline', 'Disciplinary Action / Expulsion'), ('Natural_Disaster', 'Natural Disaster / Calamity'), ('Conflict', 'Armed Conflict / Insurgency'), ('Death', 'Death of Learner'), ('Other', 'Other')], max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('intervention_attempted', models.BooleanField(default=False)),
                ('intervention_type', models.CharField(blank=True, choices=[('Home_Visit', 'Home Visit'), ('Parent_Conference', 'Parent-Teacher Conference'), ('Counseling', 'Guidance Counseling'), ('Remedial', 'Remedial Classes'), ('Financial_Assistance', 'Financial Assistance Referral'), ('Barangay_Referral', 'Barangay Referral'), ('Multiple', 'Multiple Interventions')], max_length=50)),
                ('intervention_date', models.DateField(blank=True, null=True)),
                ('intervention_outcome', models.TextField(blank=True)),
                ('guardian_notified', models.BooleanField(default=False)),
                ('guardian_notification_date', models.DateField(blank=True, null=True)),
                ('guardian_response', models.TextField(blank=True)),
                ('is_reported_to_division', models.BooleanField(default=False)),
                ('division_report_date', models.DateField(blank=True, null=True)),
                ('expected_return_sy', models.CharField(blank=True, help_text="School year the student is expected to return, e.g., '2026-2027'.", max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dropouts', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_dropouts', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_details', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Dropped Student Details',
                'verbose_name_plural': 'Dropped Student Details',
            },
        ),
        migrations.CreateModel(
            name='BalikAralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_school_year_attended', models.CharField(blank=True, max_length=9)),
                ('last_grade_level_completed', models.CharField(blank=True, max_length=50)),
                ('last_school_attended_name', models.CharField(blank=True, max_length=255)),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('years_out_of_school', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assessment_test_date', models.DateField(blank=True, null=True)),
                ('assessment_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interview_conducted_by', models.CharField(blank=True, max_length=255)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('learning_modality_preference', models.CharField(blank=True, choices=[('Face_to_Face', 'Face-to-Face'), ('Blended', 'Blended Learning'), ('Modular_Print', 'Modular (Print)'), ('Modular_Digital', 'Modular (Digital)'), ('Online', 'Online Distance Learning'), ('Homeschooling', 'Homeschooling'), ('ALS', 'Alternative Learning System')], max_length=50)),
                ('support_services_needed', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_balik_aral', to='academics.gradelevel')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balik_aral_details', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Balik-Aral Details',
                'verbose_name_plural': 'Balik-Aral Details',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PSA_Birth_Certificate', 'PSA Birth Certificate'), ('SF9_Previous', 'SF9 — Previous Report Card'), ('SF10_Form137', 'SF10 — Form 137'), ('Good_Moral', 'Certificate of Good Moral Character'), ('Medical_Certificate', 'Medical Certificate'), ('Barangay_Clearance', 'Barangay Clearance'), ('ID_Photo', 'ID Photo'), ('ESC_Certificate', 'ESC Certificate'), ('Immunization_Record', 'Immunization Record'), ('Other', 'Other')], max_length=30)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='enrollment/documents/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_documents', to='enrollment.enrollment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_enrollment_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Document',
                'verbose_name_plural': 'Enrollment Documents',
                'ordering': ['enrollment', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('Enrolled', 'Enrolled — Currently active'), ('Transferred_In', 'Transferred In — Recently moved in'), ('Transferred_Out', 'Transferred Out — Moved to another school'), ('Graduated', 'Graduated — Completed the grade level'), ('Dropped', 'Dropped — Officially dropped out'), ('Inactive', 'Inactive — Not currently attending'), ('Deceased', 'Deceased — Learner has passed away')], max_length=25, null=True)),
                ('new_status', models.CharField(choices=[('Enrolled', 'Enrolled — Currently active'), ('Transferred_In', 'Transferred In — Recently moved in'), ('Transferred_Out', 'Transferred Out — Moved to another school'), ('Graduated', 'Graduated — Completed the grade level'), ('Dropped', 'Dropped — Officially dropped out'), ('Inactive', 'Inactive — Not currently attending'), ('Deceased', 'Deceased — Learner has passed away')], max_length=25)),
                ('change_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Enrollment History Record',
                'verbose_name_plural': 'Enrollment History Records',
                'ordering': ['enrollment', '-change_date'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollment__status_c45c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school_year', 'status'], name='enrollment__school__25a5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'school_year'], name='enrollment__student_e3b2cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'school_year')},
        ),
        migrations.AddIndex(
            model_name='droppedstudentdetails',
            index=models.Index(fields=['dropout_reason'], name='enrollment__dropout_091995_idx'),
        ),
        migrations.AddIndex(
            model_name='droppedstudentdetails',
            index=models.Index(fields=['dropout_date'], name='enrollment__dropout_fb6b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentdocument',
            unique_together={('enrollment', 'document_type')},
        ),
    ]
