# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeprediction',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_predictions', to='enrollment.enrollment'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_quarters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeprediction',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_predictions', to='academics.quarter'),
        ),
        migrations.AddField(
            model_name='rpmscycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rpms_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(help_text='School this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='academics.school'),
        ),
        migrations.AddField(
            model_name='gradingschema',
            name='school',
            field=models.OneToOneField(help_text='School this grading schema belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grading_schema', to='academics.school'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this grade level belongs to (optional for global grade levels)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='academics.school'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='school',
            field=models.ForeignKey(help_text='School this school year belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='academics.school'),
        ),
        migrations.AddField(
            model_name='rpmscycle',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpms_cycles', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='gradelevelenrollmentquota',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_quotas', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mappings', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, help_text='Homeroom adviser assigned to this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Default classroom for this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academics.room'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(help_text='School this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='sectionquarterlysummary',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_summaries', to='academics.quarter'),
        ),
        migrations.AddField(
            model_name='sectionquarterlysummary',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_summaries', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='sectionquarterlysummary',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_summaries', to='academics.section'),
        ),
        migrations.AddField(
            model_name='aisectionrecommendation',
            name='section_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation', to='academics.sectionquarterlysummary'),
        ),
        migrations.AddField(
            model_name='semester',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Required for SHS subjects (1st or 2nd semester). NULL for JHS full-year subjects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_mappings', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='section',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academics.strand'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='strand',
            field=models.ForeignKey(blank=True, help_text='Only set for SHS. NULL for JHS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_mappings', to='academics.strand'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.ForeignKey(help_text='The grade level this subject is offered to.', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(help_text='School this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='strand',
            field=models.ForeignKey(blank=True, help_text='Only set for SHS specialized subjects. NULL for JHS and core SHS subjects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.strand'),
        ),
        migrations.AddField(
            model_name='sectionquarterlysummary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_summaries', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='gradeprediction',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_predictions', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='curriculummapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mappings', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='school',
            field=models.ForeignKey(help_text='School this subject group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='academics.school'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_groups', to='academics.strand'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subjects',
            field=models.ManyToManyField(help_text='Subjects that belong to this group.', related_name='subject_groups', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectprerequisite',
            name='prerequisite_subject',
            field=models.ForeignKey(help_text='The subject that must be completed first.', on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectprerequisite',
            name='subject',
            field=models.ForeignKey(help_text='The subject that requires a prerequisite.', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_of', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='track',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this track belongs to (optional for global tracks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='academics.school'),
        ),
        migrations.AddField(
            model_name='strand',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='academics.track'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('school', 'room_code')},
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('school', 'grade_code')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together={('school', 'year_label')},
        ),
        migrations.AlterUniqueTogether(
            name='quarter',
            unique_together={('school_year', 'quarter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='gradelevelenrollmentquota',
            unique_together={('school_year', 'grade_level')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('school_year', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school', 'section_name', 'grade_level', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'subject_code')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionquarterlysummary',
            unique_together={('section', 'subject', 'quarter', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculummapping',
            unique_together={('school_year', 'grade_level', 'strand', 'subject', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectgroup',
            unique_together={('school', 'group_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectprerequisite',
            unique_together={('subject', 'prerequisite_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('school', 'track_code')},
        ),
        migrations.AlterUniqueTogether(
            name='strand',
            unique_together={('track', 'strand_code')},
        ),
    ]
