# Generated by Django 6.0.6 on 2026-06-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_school_model'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingschema',
            name='school',
            field=models.OneToOneField(help_text='School this grading schema belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grading_schema', to='academics.school'),
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('cognitive_level', models.CharField(choices=[('REMEMBERING', 'Remembering (Knowledge)'), ('UNDERSTANDING', 'Understanding (Knowledge)'), ('APPLYING', 'Applying (Process)'), ('ANALYZING', 'Analyzing (Process)'), ('EVALUATING', 'Evaluating (Understanding)'), ('CREATING', 'Creating (Product)')], max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'db_table': 'academics_assessment_item',
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.assessmentitem')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.quarter')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'academics_student_assessment_result',
            },
        ),
        migrations.CreateModel(
            name='SubjectKPUPSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_knowledge', models.FloatField(default=0)),
                ('avg_process', models.FloatField(default=0)),
                ('avg_understanding', models.FloatField(default=0)),
                ('avg_product', models.FloatField(default=0)),
                ('advanced_count', models.IntegerField(default=0)),
                ('proficient_count', models.IntegerField(default=0)),
                ('developing_count', models.IntegerField(default=0)),
                ('beginning_count', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.quarter')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'db_table': 'academics_subject_kpup_summary',
            },
        ),
        migrations.CreateModel(
            name='KPUPMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_score', models.FloatField(default=0)),
                ('process_score', models.FloatField(default=0)),
                ('understanding_score', models.FloatField(default=0)),
                ('product_score', models.FloatField(default=0)),
                ('knowledge_mastery', models.CharField(blank=True, choices=[('ADVANCED', 'Advanced (96-100%)'), ('PROFICIENT', 'Proficient (86-95%)'), ('DEVELOPING', 'Developing (66-85%)'), ('BEGINNING', 'Beginning (0-65%)')], max_length=20)),
                ('process_mastery', models.CharField(blank=True, choices=[('ADVANCED', 'Advanced (96-100%)'), ('PROFICIENT', 'Proficient (86-95%)'), ('DEVELOPING', 'Developing (66-85%)'), ('BEGINNING', 'Beginning (0-65%)')], max_length=20)),
                ('understanding_mastery', models.CharField(blank=True, choices=[('ADVANCED', 'Advanced (96-100%)'), ('PROFICIENT', 'Proficient (86-95%)'), ('DEVELOPING', 'Developing (66-85%)'), ('BEGINNING', 'Beginning (0-65%)')], max_length=20)),
                ('product_mastery', models.CharField(blank=True, choices=[('ADVANCED', 'Advanced (96-100%)'), ('PROFICIENT', 'Proficient (86-95%)'), ('DEVELOPING', 'Developing (66-85%)'), ('BEGINNING', 'Beginning (0-65%)')], max_length=20)),
                ('overall_grade', models.FloatField(default=0)),
                ('overall_mastery', models.CharField(blank=True, choices=[('ADVANCED', 'Advanced (96-100%)'), ('PROFICIENT', 'Proficient (86-95%)'), ('DEVELOPING', 'Developing (66-85%)'), ('BEGINNING', 'Beginning (0-65%)')], max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.quarter')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'db_table': 'academics_kpup_mastery',
                'unique_together': {('student', 'subject', 'quarter', 'school_year')},
            },
        ),
    ]
