# Generated by Django 6.0.6 on 2026-06-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_gradingschema_school_assessmentitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(help_text="e.g., 'Mathematics', 'English', 'Science', 'Filipino'.", max_length=150)),
                ('family_code', models.CharField(help_text="e.g., 'MATH', 'ENG', 'SCI', 'FIL'.", max_length=25)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#123499', help_text="Color for charts and badges (e.g., '#2E7D32' for Science).", max_length=7)),
                ('icon_class', models.CharField(blank=True, help_text="CSS icon class for the subject family (e.g., 'fi fi-rr-calculator').", max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order in dropdowns and lists.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(help_text='School this subject family belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subject_families', to='academics.school')),
            ],
            options={
                'verbose_name': 'Subject Family',
                'verbose_name_plural': 'Subject Families',
                'db_table': 'academics_subject_family',
                'ordering': ['sort_order', 'family_name'],
                'unique_together': {('school', 'family_code')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_family',
            field=models.ForeignKey(blank=True, help_text="Optional grouping — e.g., all Math subjects belong to 'Mathematics' family.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.subjectfamily'),
        ),
    ]
