# Generated by Django 6.0.6 on 2026-06-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subjectfamily_subject_subject_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingschema',
            name='school',
            field=models.ForeignKey(help_text='School this grading schema belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemas', to='academics.school'),
        ),
    ]
