# Generated by Django 6.0.6 on 2026-06-08 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_gradingschema_school'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_items', models.PositiveSmallIntegerField()),
                ('points_per_item', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('access_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.quarter')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order_number', models.PositiveSmallIntegerField()),
                ('num_choices', models.PositiveSmallIntegerField(default=4)),
                ('correct_answer_index', models.PositiveSmallIntegerField()),
                ('choices', models.JSONField()),
                ('shuffled_choice_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.assessment')),
            ],
            options={
                'ordering': ['assessment', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='academics.assessment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.assessmentquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academics.assessmentresponse')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
    ]
