# Generated by Django 6.0.6 on 2026-06-03 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_date', models.DateField(db_index=True)),
                ('intervention_type', models.CharField(choices=[('Parent_Contact', 'Parent Contact (Phone/Message)'), ('Parent_Conference', 'Parent-Teacher Conference'), ('Home_Visit', 'Home Visit'), ('Counseling', 'Guidance Counseling'), ('Referral_Barangay', 'Referral to Barangay'), ('Referral_DSWD', 'Referral to DSWD'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='What was done during the intervention?')),
                ('outcome', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open — Ongoing'), ('Resolved', 'Resolved — Learner returned'), ('Escalated', 'Escalated — Referred to higher authority'), ('Closed', 'Closed — No further action')], db_index=True, default='Open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attendance/interventions/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_interventions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_interventions', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'Attendance Intervention',
                'verbose_name_plural': 'Attendance Interventions',
                'ordering': ['-intervention_date'],
                'indexes': [models.Index(fields=['status'], name='attendance__status_6ba748_idx'), models.Index(fields=['enrollment', 'intervention_date'], name='attendance__enrollm_9eb723_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of attendance.')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late / Tardy'), ('Excused', 'Excused Absence'), ('Cutting', 'Cutting Classes'), ('Suspended', 'Suspended')], db_index=True, default='Present', max_length=15)),
                ('time_in', models.TimeField(blank=True, help_text="Time student arrived. Required if status is 'Late'.", null=True)),
                ('minutes_late', models.PositiveSmallIntegerField(default=0, help_text='Calculated minutes late. Auto-computed from time_in vs official start time.')),
                ('excuse_type', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('Sick', 'Sick / Illness'), ('Family_Emergency', 'Family Emergency'), ('Official_Business', 'Official School Business'), ('Calamity', 'Natural Calamity / Weather'), ('Religious', 'Religious Observance'), ('Bereavement', 'Bereavement / Death in Family'), ('Other', 'Other')], help_text="Required if status is 'Excused'.", max_length=30)),
                ('excuse_note', models.TextField(blank=True, help_text='Explanation for absence or lateness.')),
                ('excuse_validated', models.BooleanField(default=False, help_text='Has the excuse been verified by the class adviser?')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('is_holiday', models.BooleanField(default=False, help_text='Was this day a holiday? Attendance not required.')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='The enrollment record for this school year.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='enrollment.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Teacher who recorded this attendance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'enrollment__student__last_name'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx'), models.Index(fields=['enrollment', 'date'], name='attendance__enrollm_9fc2c3_idx'), models.Index(fields=['status', 'date'], name='attendance__status_15e5cd_idx')],
                'unique_together': {('enrollment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number: 1=June, 2=July, ..., 12=May.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_school_days', models.PositiveSmallIntegerField(default=0)),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('days_late', models.PositiveSmallIntegerField(default=0)),
                ('days_excused', models.PositiveSmallIntegerField(default=0)),
                ('days_cutting', models.PositiveSmallIntegerField(default=0)),
                ('days_suspended', models.PositiveSmallIntegerField(default=0)),
                ('absence_rate_percent', models.DecimalField(blank=True, decimal_places=2, help_text='(days_absent / total_school_days) * 100.', max_digits=5, null=True)),
                ('is_at_risk', models.BooleanField(db_index=True, default=False, help_text='≥20% absence rate triggers DepEd intervention.')),
                ('consecutive_absences', models.PositiveSmallIntegerField(default=0, help_text='Maximum consecutive days absent this month.')),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='enrollment.enrollment')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='academics.schoolyear')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['school_year', 'month', 'enrollment__student__last_name'],
                'indexes': [models.Index(fields=['is_at_risk'], name='attendance__is_at_r_772998_idx'), models.Index(fields=['school_year', 'month'], name='attendance__school__5c5cbc_idx')],
                'unique_together': {('enrollment', 'month', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='SF2AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('report_year', models.PositiveSmallIntegerField()),
                ('total_enrollment', models.PositiveSmallIntegerField(default=0, help_text='Number of enrolled learners in this section.')),
                ('total_male', models.PositiveSmallIntegerField(default=0)),
                ('total_female', models.PositiveSmallIntegerField(default=0)),
                ('average_daily_attendance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_dropouts_this_month', models.PositiveSmallIntegerField(default=0)),
                ('total_transferred_out_this_month', models.PositiveSmallIntegerField(default=0)),
                ('total_transferred_in_this_month', models.PositiveSmallIntegerField(default=0)),
                ('chronically_absent_count', models.PositiveSmallIntegerField(default=0, help_text='Learners with ≥20% absences.')),
                ('interventions_conducted', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted to Registrar'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Returned', 'Returned for Revision')], db_index=True, default='Draft', max_length=20)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attendance/sf2/%Y/%m/')),
                ('is_submitted_to_division', models.BooleanField(default=False)),
                ('division_submission_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_sf2_reports', to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(blank=True, help_text='Grading quarter this report covers. Nullable per master schema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf2_reports', to='academics.quarter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sf2_reports', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf2_reports', to='academics.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf2_reports', to='academics.section')),
            ],
            options={
                'verbose_name': 'SF2 Attendance Report',
                'verbose_name_plural': 'SF2 Attendance Reports',
                'ordering': ['-school_year__year_start', 'section__section_name', 'report_month'],
                'unique_together': {('section', 'school_year', 'quarter', 'report_month')},
            },
        ),
    ]
